# Travis CI build file

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - /^issue.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.0
    - os: osx
      osx_image: xcode9
      sudo: required
      env: SWIFT_SNAPSHOT=4.0

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

  # install Mosquitto broker for testing 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo | sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y mosquitto  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mosquitto -c /etc/mosquitto/mosquitto.conf -d ; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install curl mosquitto openssl ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/sbin/mosquitto -c /usr/local/etc/mosquitto/mosquitto.conf -d   ; fi

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR 